### ISSUE TITLE
Playback failures for archived ugoiras

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#3576]
From [forum #143713](https://danbooru.donmai.us/forum_posts/143713):

> When I try to watch ugoiras in original mode, they won’t play and I get this in the Firefox console:

>> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://hijiribe.donmai.us/data/[MD5].zip. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

![image](https://user-images.githubusercontent.com/8430473/37636748-d4c6efa6-2bd1-11e8-85b4-3b35cc89f0fc.png)

Example: [post #2999841](https://danbooru.donmai.us/posts/2999841?original=1). The ugoira player wants to download the .zip file, which fails when the user is on danbooru.donmai.us but the .zip file is on hijiribe.donmai.us. Nginx needs to be configured to return the proper CORS headers to allow this request. These are the headers that Pixiv returns:

![image](https://user-images.githubusercontent.com/8430473/37636954-204d2ec6-2bd3-11e8-841b-2db323382e48.png)

**Comment by r888888888** [comment]
This is fixed now.

**Comment by evazion** [comment]
Reported to be happening again on raikou2: https://danbooru.donmai.us/forum_topics/9127?page=260#forum_post_151705.

**Comment by evazion** [comment]
https://danbooru.donmai.us/posts?tags=id%3A<2000000+ugoira+filetype%3Azip
https://danbooru.donmai.us/posts/1999815?original=1

Still broken. CORS headers on raikou2 need to be configured as per https://enable-cors.org/server_nginx.html.

**Comment by nonamethanks** [comment]
Closing this issue as it seems to be solved, all examples above correctly play now.
