### ISSUE TITLE
Batch bookmarklet thumbnails are broken or not working as expected

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#3891]
Related to issue #3880.

For Pixiv, it's using the correct 240x240 links for the image proxy, however none of the thumbnails are loading.
![image](https://user-images.githubusercontent.com/21149935/45401005-92de4f00-b603-11e8-9fd5-5308cb7fd228.png)

https://danbooru.donmai.us/uploads/image_proxy?url=https%3A%2F%2Fi.pximg.net%2Fc%2F240x240%2Fimg-master%2Fimg%2F2018%2F05%2F17%2F13%2F09%2F45%2F68785739_p0.jpg

The image proxy link above produces the following exception when you follow it:

```
RuntimeError exception raised
HTTP error code: 404 Not Found
app/logical/image_proxy.rb:23:in `get_image'
app/controllers/uploads_controller.rb:22:in `image_proxy'
```

For both Twitter and Tumblr, it's still loading the ``:orig`` and the ``_1280`` sized images for the thumbnails, and not using the ``:small`` and the ``_250`` sized images.

**Comment by r888888888** [comment]
@evazion's fix was deployed.

**Comment by evazion** [comment]
0df5937 fixes Twitter/Tumblr using the full images.

There's still an issue with ugoiras and Twitter videos not finding the correct thumbnails.

**Comment by BrokenEagle** [comment]
I believe that this has already been fixed, so I'm closing it for now.
